### PR TITLE
Small Updates (and error fixing)

### PR DESCRIPTION
**Pull request by TheAdamGalloway**
Just a few small tweaks

+Added a cleaner option to purge old posts, eliminating the caching error when rebuilding boards.

### CODE REVIEW

**Comment by TheAdamGalloway** [comment]
Sorry for all the commits, I tested the solution and had to reiterate it.

**Comment by TheAdamGalloway** [comment]
Anyone? @Desuneko @malkovich @skandaI

**Comment by skandaI** [comment]
This repository is dead. We develop independent repository only for site karachan.org. Keep your changes on your fork.

**Comment by TheAdamGalloway** [comment]
@skandaI That's a shame, sharing is caring!

**Pull request closed without merging**
